services:
  - type: web
    name: mlpulse-web
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py setup_site"
    startCommand: "gunicorn mlpulse.wsgi:application --workers 2 --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: GROQ_API_KEY
        sync: false
      - key: AUTO_PUBLISH
        value: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
